server:
  port: 8080
  address: 0.0.0.0
  servlet:
    session:
      timeout: 30m
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASS}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASS}
    port: 587
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  session:
    jdbc:
      initialize-schema: always
springdoc:
  swagger-ui:
    path: /api-docs
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  name: yalli
