spring:
  datasource:
    username: postgres
    password: 10062005
    url: jdbc:postgresql://localhost:5432/yalli
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.ethereal.email
    username: delmer.dubuque81@ethereal.email
    password: qG4QpxHpNhTqJGzXk1
    port: 587
server:
  port: 8085