spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
              - openid
  datasource:
    username: postgres
    password: ${LOCAL_DB_PASS}
    url: ${LOCAL_DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      initialize-schema: always
server:
  port: 8085
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
logging:
  level:
    org:
      springframework:
        security: trace
springdoc:
  swagger-ui:
    path: /api-docs