spring:
  datasource:
    username: yalli_database_8aka_user
    password: z9pu03Ay1hOqOiOB1s7HRvaqEFuf10H1
    url: jdbc:postgresql://dpg-ctttsfd2ng1s7398mmd0-a.oregon-postgres.render.com/yalli_database_8aka
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: yalli.org@gmail.com
    password: buzdocbljwcwmrbe
    port: 587
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /api-docs
minio:
  url: https://minio-server-nlle.onrender.com
  access-key: p6YUJOQerHh0bPoKHC9OwYg502JL5YiGzZYcq+DRjFs=
  secret-key: ZuwU65NA0FNVjQb4X31XSz1Nk1hic5mRWnkM7KwSNYA=
  name: yalli
