spring:
  datasource:
    username: postgres
    password: 10062005
    url: jdbc:postgresql://localhost:5432/yalli
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8085
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
logging:
  level:
    org:
      springframework:
        security: trace
springdoc:
  swagger-ui:
    path: /api-docs