spring:
  datasource:
    username: yalli_database_user
    password: 96wcKHXbang2yV8lmeppDMo7iueFsmK7
    url: jdbc:postgresql://dpg-crm96mu8ii6s73ambocg-a.frankfurt-postgres.render.com/yalli_database
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: texnoera.academy@gmail.com
    password: sjqmzjnzbyxxlusr
    port: 587
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true
springdoc:
  swagger-ui:
    path: /api-docs
