server:
  port: 9999
  address: 0.0.0.0
  servlet:
    session:
      timeout: 30000m
      tracking-modes: cookie
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 795022314333-7pqo4hij4bngjktk6ph58vfvc9t2932b.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              - openid
        provider:
          google:
            authorization-uri:
              https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri:
              https://www.googleapis.com/oauth2/v3/userinfo

  datasource:
    username: yalli_database_8aka_user
    password: z9pu03Ay1hOqOiOB1s7HRvaqEFuf10H1
    url: jdbc:postgresql://dpg-ctttsfd2ng1s7398mmd0-a.oregon-postgres.render.com/yalli_database_8aka
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  mail:
    host: smtp.gmail.com
    username: yalli.org@gmail.com
    password: buzdocbljwcwmrbe
    port: 587
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  session:
    jdbc:
      initialize-schema: embedded
springdoc:
  swagger-ui:
    path: /api-docs
minio:
  url: https://minio-server-nlle.onrender.com
  access-key: p6YUJOQerHh0bPoKHC9OwYg502JL5YiGzZYcq+DRjFs=
  secret-key: ZuwU65NA0FNVjQb4X31XSz1Nk1hic5mRWnkM7KwSNYA=
  name: yalli
logging:
  level:
    org:
      springframework:
        security: TRACE
