server:
  port: 8080
  address: 0.0.0.0
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - email
              - profile
              - openid
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: yalli.org@gmail.com
    password: ${MAIL_PASS}
    port: 587
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  session:
    jdbc:
      initialize-schema: embedded
springdoc:
  swagger-ui:
    path: /api-docs
minio:
  url: https://minio-server-nlle.onrender.com
  access-key: ${MINIO_ACCESS}
  secret-key: ${MINIO_SECRET}
  name: yalli